export const routes = [
  {
    id: 0,
    name: "Đà Lạt – Đức Trọng",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_1.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 1,
    name: "Đà Lạt – Đơn Dương",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_2.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 2,
    name: "Đà Lạt – Lạc Dương",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_3.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 3,
    name: "Đà Lạt – Bảo Lộc",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_4.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 4,
    name: "Đà Lạt – Xuân Trường",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_5.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 5,
    name: "Đà Lạt – Phú Sơn",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_6.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 6,
    name: "Liên nghĩa – Tân Thanh",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_7.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 7,
    name: "Đà Lạt – Liên Khương",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_8.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 8,
    name: "Đà Lạt – Đại Lào",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_9.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
  {
    id: 9,
    name: "Đà Lạt – Thái Phiên",
    desc: "Tuyến xe từ Đà Lạt tới bla bla với mã số chuyến xe là 12345 và số giãn cách",
    imgUrl: "bus_10.png",
    unit: "Công ty cổ phần Lâm Đồng",
    phone: "02633822120",
    length: "35km",
    time: "5h30 - 9h00",
    spacing: "15 - 30 phút / chuyến",
    number: "70",
    route:
      "Bến xe buýt Mai Anh Đào – Đường Phù Đổng Thiên Vương – Đường Đinh Tiên Hoàng - Đường Nguyễn Thái Học - Đường Lê Đại Hành - Khu Hoà Bình – Đường 3/2 – Đường Trần Phú – Đường 3/4 - Quốc lộ 20 - Bến xe Đức Trọng và ngược lại.",
  },
];
