  import Head from 'next/head'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between items-center px-global py-4">
        <Link href="/" className="text-accent font-mavenpro font-bold text-lg">DALATBUS</Link>
        <div className="">ljfsdjkfaf</div>
        <div className="">ljfsdjkfaf</div>
      </div>
    </>
  );
}
